#include "p-load.h"

enum PloaderTypeIds
{
    ID_NONE = 0,
    ID_P_STAR_25K50_BOOTLOADER,
    ID_P_STAR_45K50_BOOTLOADER,
    ID_PGM04A_BOOTLOADER,
    ID_PGM04A_APP,
    ID_PGM04B_BOOTLOADER,
    ID_PGM04B_APP,
    ID_TIC_T825_BOOTLOADER,
    ID_TIC_T825_APP,
    ID_TIC_T834_BOOTLOADER,
    ID_TIC_T834_APP,
    ID_TIC_T500_BOOTLOADER,
    ID_TIC_T500_APP,
    ID_JRK_UMC04A_30V_BOOTLOADER,
    ID_JRK_UMC04A_30V_APP,
    ID_JRK_UMC04A_40V_BOOTLOADER,
    ID_JRK_UMC04A_40V_APP,
    ID_JRK_UMC05A_30V_BOOTLOADER,
    ID_JRK_UMC05A_30V_APP,
    ID_JRK_UMC05A_40V_BOOTLOADER,
    ID_JRK_UMC05A_40V_APP,
#ifndef NDEBUG
    ID_SMC_18V25_BOOTLOADER,
    ID_SMC_18V25_APP,
#endif
};

const std::vector<PloaderAppType> ploaderAppTypes = {
    {
        /* id */ ID_PGM04A_APP,
        /* usbVendorId */ 0x1FFB,
        /* usbProductId */ 0x00B0,
        /* name */ "Pololu USB AVR Programmer v2",
        /* composite */ true,
        /* interfaceNumber */ 0,
    },
    {
        /* id */ ID_PGM04B_APP,
        /* usbVendorId */ 0x1FFB,
        /* usbProductId */ 0x00BB,
        /* name */ "Pololu USB AVR Programmer v2.1",
        /* composite */ true,
        /* interfaceNumber */ 0,
    },
    {
        /* id */ ID_TIC_T825_APP,
        /* usbVendorId */ 0x1FFB,
        /* usbProductId */ 0x00B3,
        /* name */ "Tic T825",
        /* composite */ false,
        /* interfaceNumber */ 0,
    },
    {
        /* id */ ID_TIC_T834_APP,
        /* usbVendorId */ 0x1FFB,
        /* usbProductId */ 0x00B5,
        /* name */ "Tic T834",
        /* composite */ false,
        /* interfaceNumber */ 0,
    },
    {
        /* id */ ID_TIC_T500_APP,
        /* usbVendorId */ 0x1FFB,
        /* usbProductId */ 0x00BD,
        /* name */ "Tic T500",
        /* composite */ false,
        /* interfaceNumber */ 0,
    },
    {
        /* id */ ID_JRK_UMC04A_30V_APP,
        /* usbVendorId */ 0x1FFB,
        /* usbProductId */ 0x00B7,
        /* name */ "Jrk G2 18v27",
        /* composite */ true,
        /* interfaceNumber */ 0,
    },
    {
        /* id */ ID_JRK_UMC04A_40V_APP,
        /* usbVendorId */ 0x1FFB,
        /* usbProductId */ 0x00B9,
        /* name */ "Jrk G2 24v21",
        /* composite */ true,
        /* interfaceNumber */ 0,
    },
    {
        /* id */ ID_JRK_UMC05A_30V_APP,
        /* usbVendorId */ 0x1FFB,
        /* usbProductId */ 0x00BF,
        /* name */ "Jrk G2 18v19",
        /* composite */ true,
        /* interfaceNumber */ 0,
    },
    {
        /* id */ ID_JRK_UMC05A_40V_APP,
        /* usbVendorId */ 0x1FFB,
        /* usbProductId */ 0x00C1,
        /* name */ "Jrk G2 24v13",
        /* composite */ true,
        /* interfaceNumber */ 0,
    },
#ifndef NDEBUG
    {
        /* id */ ID_SMC_18V25_APP,
        /* usbVendorId */ 0x1FFB,
        /* usbProductId */ 0x009C,
        /* name */ "Pololu Simple High-Power Motor Controller 18v25",
        /* composite */ true,
        /* interfaceNumber */ 2,
    },
#endif
};

const std::vector<PloaderType> ploaderTypes = {
    {
        /* id */ ID_P_STAR_25K50_BOOTLOADER,
        /* usbVendorId */ 0x1FFB,
        /* usbProductId */ 0x0102,
        /* name */ "Pololu P-Star 25K50 Bootloader",
        /* appAddress */ 0x2000,
        /* appSize */ 0x6000,
        /* writeBlockSize */ 0x40,
        /* erasingFlashAffectsEeprom */ false,
        /* supportsFlashPlainWriting */ true,
        /* supportsFlashReading */ true,
        /* eepromAddress */ 0,
        /* eepromAddressHexFile */ 0xF00000,
        /* eepromSize */ 0x100,
        /* supportsEepromAccess */ true,
        /* deviceCode */ NULL,
        /* matchingAppTypes */ { },
    },
    {
        /* id */ ID_P_STAR_45K50_BOOTLOADER,
        /* usbVendorId */ 0x1FFB,
        /* usbProductId */ 0x0103,
        /* name */ "Pololu P-Star 45K50 Bootloader",
        /* appAddress */ 0x2000,
        /* appSize */ 0x6000,
        /* writeBlockSize */ 0x40,
        /* erasingFlashAffectsEeprom */ false,
        /* supportsFlashPlainWriting */ true,
        /* supportsFlashReading */ true,
        /* eepromAddress */ 0,
        /* eepromAddressHexFile */ 0xF00000,
        /* eepromSize */ 0x100,
        /* supportsEepromAccess */ true,
        /* deviceCode */ NULL,
        /* matchingAppTypes */ { },
    },
    {
        /* id */ ID_PGM04A_BOOTLOADER,
        /* usbVendorId */ 0x1FFB,
        /* usbProductId */ 0x00AF,
        /* name */ "Pololu USB AVR Programmer v2 Bootloader",
        /* appAddress */ 0x2000,
        /* appSize */ 0x6000,
        /* writeBlockSize */ 0x40,
        /* erasingFlashAffectsEeprom */ true,
        /* supportsFlashPlainWriting */ false,
        /* supportsFlashReading */ false,
        /* eepromAddress */ 0,
        /* eepromAddressHexFile */ 0xF00000,
        /* eepromSize */ 0x100,
        /* supportsEepromAccess */ true,
        /* deviceCode */ NULL,
        /* matchingAppTypes */ { ID_PGM04A_APP },
    },
    {
        /* id */ ID_PGM04B_BOOTLOADER,
        /* usbVendorId */ 0x1FFB,
        /* usbProductId */ 0x00BA,
        /* name */ "Pololu USB AVR Programmer v2.1 Bootloader",
        /* appAddress */ 0x2000,
        /* appSize */ 0x6000,
        /* writeBlockSize */ 0x40,
        /* erasingFlashAffectsEeprom */ true,
        /* supportsFlashPlainWriting */ false,
        /* supportsFlashReading */ false,
        /* eepromAddress */ 0,
        /* eepromAddressHexFile */ 0xF00000,
        /* eepromSize */ 0x100,
        /* supportsEepromAccess */ true,
        /* deviceCode */ NULL,
        /* matchingAppTypes */ { ID_PGM04B_APP },
    },
    {
        /* id */ ID_TIC_T825_BOOTLOADER,
        /* usbVendorId */ 0x1FFB,
        /* usbProductId */ 0x00B2,
        /* name */ "Tic T825 Bootloader",
        /* appAddress */ 0x2000,
        /* appSize */ 0x6000,
        /* writeBlockSize */ 0x40,
        /* erasingFlashAffectsEeprom */ true,
        /* supportsFlashPlainWriting */ false,
        /* supportsFlashReading */ false,
        /* eepromAddress */ 0,
        /* eepromAddressHexFile */ 0xF00000,
        /* eepromSize */ 0x100,
        /* supportsEepromAccess */ true,
        /* deviceCode */ NULL,
        /* matchingAppTypes */ { ID_TIC_T825_APP },
    },
    {
        /* id */ ID_TIC_T834_BOOTLOADER,
        /* usbVendorId */ 0x1FFB,
        /* usbProductId */ 0x00B4,
        /* name */ "Tic T834 Bootloader",
        /* appAddress */ 0x2000,
        /* appSize */ 0x6000,
        /* writeBlockSize */ 0x40,
        /* erasingFlashAffectsEeprom */ true,
        /* supportsFlashPlainWriting */ false,
        /* supportsFlashReading */ false,
        /* eepromAddress */ 0,
        /* eepromAddressHexFile */ 0xF00000,
        /* eepromSize */ 0x100,
        /* supportsEepromAccess */ true,
        /* deviceCode */ NULL,
        /* matchingAppTypes */ { ID_TIC_T834_APP },
    },
    {
        /* id */ ID_TIC_T500_BOOTLOADER,
        /* usbVendorId */ 0x1FFB,
        /* usbProductId */ 0x00BC,
        /* name */ "Tic T500 Bootloader",
        /* appAddress */ 0x2000,
        /* appSize */ 0x6000,
        /* writeBlockSize */ 0x40,
        /* erasingFlashAffectsEeprom */ true,
        /* supportsFlashPlainWriting */ false,
        /* supportsFlashReading */ false,
        /* eepromAddress */ 0,
        /* eepromAddressHexFile */ 0xF00000,
        /* eepromSize */ 0x100,
        /* supportsEepromAccess */ true,
        /* deviceCode */ NULL,
        /* matchingAppTypes */ { ID_TIC_T500_APP },
    },
    {
        /* id */ ID_JRK_UMC04A_30V_BOOTLOADER,
        /* usbVendorId */ 0x1FFB,
        /* usbProductId */ 0x00B6,
        /* name */ "Jrk G2 18v27 Bootloader",
        /* appAddress */ 0x2000,
        /* appSize */ 0x6000,
        /* writeBlockSize */ 0x40,
        /* erasingFlashAffectsEeprom */ true,
        /* supportsFlashPlainWriting */ false,
        /* supportsFlashReading */ false,
        /* eepromAddress */ 0,
        /* eepromAddressHexFile */ 0xF00000,
        /* eepromSize */ 0x100,
        /* supportsEepromAccess */ true,
        /* deviceCode */ NULL,
        /* matchingAppTypes */ { ID_JRK_UMC04A_30V_APP },
    },
    {
        /* id */ ID_JRK_UMC04A_40V_BOOTLOADER,
        /* usbVendorId */ 0x1FFB,
        /* usbProductId */ 0x00B8,
        /* name */ "Jrk G2 24v21 Bootloader",
        /* appAddress */ 0x2000,
        /* appSize */ 0x6000,
        /* writeBlockSize */ 0x40,
        /* erasingFlashAffectsEeprom */ true,
        /* supportsFlashPlainWriting */ false,
        /* supportsFlashReading */ false,
        /* eepromAddress */ 0,
        /* eepromAddressHexFile */ 0xF00000,
        /* eepromSize */ 0x100,
        /* supportsEepromAccess */ true,
        /* deviceCode */ NULL,
        /* matchingAppTypes */ { ID_JRK_UMC04A_40V_APP },
    },
    {
        /* id */ ID_JRK_UMC05A_30V_BOOTLOADER,
        /* usbVendorId */ 0x1FFB,
        /* usbProductId */ 0x00BE,
        /* name */ "Jrk G2 18v19 Bootloader",
        /* appAddress */ 0x2000,
        /* appSize */ 0x6000,
        /* writeBlockSize */ 0x40,
        /* erasingFlashAffectsEeprom */ true,
        /* supportsFlashPlainWriting */ false,
        /* supportsFlashReading */ false,
        /* eepromAddress */ 0,
        /* eepromAddressHexFile */ 0xF00000,
        /* eepromSize */ 0x100,
        /* supportsEepromAccess */ true,
        /* deviceCode */ NULL,
        /* matchingAppTypes */ { ID_JRK_UMC05A_30V_APP },
    },
    {
        /* id */ ID_JRK_UMC05A_40V_BOOTLOADER,
        /* usbVendorId */ 0x1FFB,
        /* usbProductId */ 0x00C0,
        /* name */ "Jrk G2 24v13 Bootloader",
        /* appAddress */ 0x2000,
        /* appSize */ 0x6000,
        /* writeBlockSize */ 0x40,
        /* erasingFlashAffectsEeprom */ true,
        /* supportsFlashPlainWriting */ false,
        /* supportsFlashReading */ false,
        /* eepromAddress */ 0,
        /* eepromAddressHexFile */ 0xF00000,
        /* eepromSize */ 0x100,
        /* supportsEepromAccess */ true,
        /* deviceCode */ NULL,
        /* matchingAppTypes */ { ID_JRK_UMC05A_40V_APP },
    },
#ifndef NDEBUG
    {
        /* id */ ID_SMC_18V25_BOOTLOADER,
        /* usbVendorId */ 0x1FFB,
        /* usbProductId */ 0x009B,
        /* name */ "Pololu Simple High-Power Motor Controller 18v25 Bootloader",
        /* appAddress */ 0x08002000,
        /* appSize */ 0xE000,
        /* writeBlockSize */ 0x40,
        /* erasingFlashAffectsEeprom */ true,
        /* supportsFlashPlainWriting */ false,
        /* supportsFlashReading */ false,
        /* eepromAddress */ 0,
        /* eepromAddressHexFile */ 0,
        /* eepromSize */ 0,
        /* supportsEepromAccess */ false,
        /* deviceCode */ NULL,
        /* matchingAppTypes */ { ID_SMC_18V25_APP },
    },
#endif
};

const std::vector<PloaderUserType> ploaderUserTypes = {
    {
        /* codeName */ "p-star",
        /* name */ "Pololu P-Star",
        /* memberIds */ { ID_P_STAR_25K50_BOOTLOADER, ID_P_STAR_45K50_BOOTLOADER },
    },
    {
        /* codeName */ "p-star-25k50",
        /* name */ "Pololu P-Star 25K50",
        /* memberIds */ { ID_P_STAR_25K50_BOOTLOADER },
    },
    {
        /* codeName */ "p-star-45k50",
        /* name */ "Pololu P-Star 45K50",
        /* memberIds */ { ID_P_STAR_45K50_BOOTLOADER },
    },
    {
        /* codeName */ "pavr2",
        /* name */ "Pololu USB AVR Programer v2.x",
        /* memberIds */ { ID_PGM04A_BOOTLOADER, ID_PGM04A_APP,
                          ID_PGM04B_BOOTLOADER, ID_PGM04B_APP }
    },
    {
        /* codeName */ "pgm04a",
        /* name */ "Pololu USB AVR Programmer v2",
        /* memberIds */ { ID_PGM04A_BOOTLOADER, ID_PGM04A_APP },
    },
    {
        /* codeName */ "pgm04b",
        /* name */ "Pololu USB AVR Programmer v2.1",
        /* memberIds */ { ID_PGM04B_BOOTLOADER, ID_PGM04B_APP },
    },
    {
        /* codeName */ "tic",
        /* name */ "Tic",
        /* memberIds */ { ID_TIC_T825_BOOTLOADER, ID_TIC_T825_APP,
                          ID_TIC_T834_BOOTLOADER, ID_TIC_T834_APP,
                          ID_TIC_T500_BOOTLOADER, ID_TIC_T500_APP },
    },
    {
        /* codeName */ "tic-t825",
        /* name */ "Tic T825",
        /* memberIds */ { ID_TIC_T825_BOOTLOADER, ID_TIC_T825_APP },
    },
    {
        /* codeName */ "tic-t834",
        /* name */ "Tic T834",
        /* memberIds */ { ID_TIC_T834_BOOTLOADER, ID_TIC_T834_APP },
    },
    {
        /* codeName */ "tic-t500",
        /* name */ "Tic T500",
        /* memberIds */ { ID_TIC_T500_BOOTLOADER, ID_TIC_T500_APP },
    },
    {
        /* codeName */ "jrk",
        /* name */ "Jrk G2",
        /* memberIds */ { ID_JRK_UMC04A_30V_APP, ID_JRK_UMC04A_30V_BOOTLOADER,
                          ID_JRK_UMC04A_40V_APP, ID_JRK_UMC04A_40V_BOOTLOADER,
                          ID_JRK_UMC05A_30V_APP, ID_JRK_UMC05A_30V_BOOTLOADER,
                          ID_JRK_UMC05A_40V_APP, ID_JRK_UMC05A_40V_BOOTLOADER },
    },
    {
        /* codeName */ "jrk-18v27",
        /* name */ "Jrk G2 18v27",
        /* memberIds */ { ID_JRK_UMC04A_30V_APP, ID_JRK_UMC04A_30V_BOOTLOADER },
    },
    {
        /* codeName */ "jrk-24v21",
        /* name */ "Jrk G2 24v21",
        /* memberIds */ { ID_JRK_UMC04A_40V_APP, ID_JRK_UMC04A_40V_BOOTLOADER },
    },
    {
        /* codeName */ "jrk-18v19",
        /* name */ "Jrk G2 18v19",
        /* memberIds */ { ID_JRK_UMC05A_30V_APP, ID_JRK_UMC05A_30V_BOOTLOADER },
    },
    {
        /* codeName */ "jrk-24v13",
        /* name */ "Jrk G2 24v13",
        /* memberIds */ { ID_JRK_UMC05A_40V_APP, ID_JRK_UMC05A_40V_BOOTLOADER },
    },
#ifndef NDEBUG
    {
        /* codeName */ "smc",
        /* name */ "Pololu Simple Motor Controller",
        /* memberIds */ { ID_SMC_18V25_APP, ID_SMC_18V25_BOOTLOADER },
    },
#endif
};
